/**
 * Demand Letter rendering — architecture.md §5.6, §8.3; `demo-safety`.
 *
 * Every word this file prints is either a constant below or a value from
 * `LetterModel`, which pure domain code built from the ledger, the reviewed
 * rule table and the arithmetic in `domain/claim`. **Nothing here is
 * model-generated**, and there is no code path by which it could be: the
 * renderer never sees a model, a prompt or a port.
 *
 * §8.3's sequence has the worker ask Bedrock to "compose narrative only, facts
 * injected as data". That step is deliberately not built — see the header of
 * `domain/documents/letter-model.ts`. A fabricated sentence in a demand letter
 * is the single most expensive error this system could make.
 *
 * ── The copy rules, enforced here ───────────────────────────────────────────
 *  - **Tamper-evidence, never admissibility.** The annexure says what the
 *    record *is* — dated, hashed, unmodified since capture. Never what a court
 *    will accept, never "proof", never "certified".
 *  - **No verdict.** The letter asserts a debt, which is arithmetic, and never
 *    asserts fault, which is not. The landlord's stated reasons are printed as
 *    their assertions and are neither adopted nor rebutted.
 *  - **No legal advice.** Said in the letter's own words, because a document
 *    that names a statute and a forum reads as advice unless it denies being
 *    it.
 *  - **R9: an unreviewed rule table says so.** `rules.reviewed` is false
 *    whenever `data/state-rules/KA.json` ships without `lastReviewedAt`, and
 *    the caveat below is what the tenant and the landlord both see.
 *  - **A visible marker on every model-derived assertion**, distinct from one
 *    the tenant wrote.
 *  - **No confidence figure**, at any provenance (§9.2).
 *
 * ── Determinism ─────────────────────────────────────────────────────────────
 * Like the report: fixed metadata dates taken from the model, no document id,
 * so re-rendering the same model reproduces the same bytes and therefore the
 * same document hash.
 */
import { PDFDocument, StandardFonts } from 'pdf-lib';
import { formatRupees } from '@handover/shared';
import { CONTENT_WIDTH, Canvas, MUTED, drawFooters, wrap } from './canvas.js';
import type { Fonts } from './canvas.js';
import type { LetterModel, LetterRoom } from '../../domain/documents/letter-model.js';
import type { RecordedChange, ReportPhoto } from '../../domain/documents/report-model.js';

/* ── Fixed copy ────────────────────────────────────────────────────────────── */

const TITLE = 'Demand for Return of Security Deposit';

const OPENING = [
  'This letter sets out the security deposit still outstanding on the tenancy below, the',
  'figures it is calculated from, and the record of the property’s condition that supports it.',
  'Every amount stated here is arithmetic over the figures in the summary; every photograph',
  'referenced in the annexure was timestamped and hashed by this service when it was received.',
];

/**
 * The integrity statement, matched to the report's.
 *
 * Three claims, each of which the system can actually support: we recorded
 * these at these times by our clock, this is the digest of what we stored, the
 * stored object has not been rewritten. The last line weakens the document and
 * stays in anyway — a reader who discovers it themselves has been misled by
 * its absence.
 */
const ANNEXURE_NOTE = [
  'Each photograph listed below was timestamped by this service when it was received, and a',
  'SHA-256 digest was computed from the stored file at that moment. The stored files are never',
  'rewritten, so a digest recomputed from one today will match the value printed here if and',
  'only if the file is unchanged since capture. These digests are generated by this service and',
  'are evidence of tamper-evidence, not of authenticity independently certified by a third party.',
];

const CHANGES_NOTE = [
  'The tenant recorded the following changes between the two sets of photographs, and has',
  'reviewed and accepted each one. Each entry is shown with how it came to be on this record.',
  'This letter reaches no conclusion about who caused any change, or about whether any change',
  'is normal wear and tear.',
];

/**
 * The closing caveats. Not boilerplate — each line denies a specific thing a
 * reader would otherwise reasonably infer from a letter that cites a statute
 * and names a court.
 */
const DISCLAIMER = [
  'This letter was prepared by the tenant using Handover, a self-service tool. It is not legal',
  'advice, and no solicitor or advocate has reviewed it or the tenancy it describes. The',
  'statutory references above are provided so the recipient can check them at source.',
];

/** Shown whenever the rule table carries no review date (R9). */
const RULES_UNREVIEWED = [
  'The statutory references, deadlines and forum named in this letter have not been verified by',
  'a qualified person. They are drafted from secondary sources and should be checked against',
  'the primary legislation before either party relies on them.',
];

const ORIGIN_LABEL: Readonly<Record<RecordedChange['origin'], string>> = {
  TENANT_RECORDED: 'Recorded by the tenant',
  TENANT_ACCEPTED_SUGGESTION: 'Software suggestion, reviewed and accepted by the tenant',
};

/* ── Small formatters ──────────────────────────────────────────────────────── */

/**
 * Basis points as a percentage, exactly.
 *
 * Integer arithmetic on the way out, the same as on the way in: `600 / 100`
 * cannot lose a digit, whereas formatting a float rate could round 6.005 into
 * something that does not match the figure the interest was computed from.
 */
function formatBps(bps: number): string {
  return `${Math.trunc(bps / 100)}.${String(bps % 100).padStart(2, '0')}%`;
}

/**
 * An amount, with the currency named in words.
 *
 * Not the rupee sign: U+20B9 is outside WinAnsi, so the standard PDF fonts
 * cannot draw it and `sanitise` drops it — which would leave every figure on
 * the page a bare number. "INR" is unambiguous, encodable, and survives being
 * photocopied, faxed and re-typed, which is what happens to a letter like
 * this one.
 */
const money = (paise: number): string => `INR ${formatRupees(paise as never, { symbol: false })}`;

/* ── Sections ──────────────────────────────────────────────────────────────── */

/** A label/value row, drawn as one line so the figures line up down the page. */
function figure(canvas: Canvas, label: string, value: string, bold = false): void {
  canvas.text(`${label}:  ${value}`, { size: 10, bold });
}

function drawSummary(canvas: Canvas, model: LetterModel): void {
  const { claim } = model;

  canvas.text('The deposit and what remains outstanding', { size: 12, bold: true });
  canvas.rule();

  figure(canvas, 'Security deposit paid', money(claim.depositPaise));
  figure(canvas, 'Deductions claimed by the landlord', money(claim.claimedDeductionsPaise));

  if (claim.deductionsExceedDeposit) {
    // Stated, not silently floored. The arithmetic clamps the expected refund
    // at zero; a reader has to be told that is what happened.
    for (const line of wrap(
      'The deductions claimed exceed the deposit held. The refund below is calculated as nil ' +
        'rather than as a negative amount; no sum is owed by the tenant on account of this.',
      canvas.font.body,
      9,
    )) {
      canvas.text(line, { size: 9, color: MUTED });
    }
  }

  figure(canvas, 'Refund due after deductions', money(claim.expectedRefundPaise));
  figure(canvas, 'Amount returned to the tenant', money(claim.amountReceivedPaise));
  canvas.gap(4);
  figure(canvas, 'Deposit still outstanding', money(claim.outstanding.amount), true);

  if (claim.interest.claimed) {
    const { amount, rateBps, days, fromDate, toDate } = claim.interest;
    figure(canvas, `Statutory interest of ${formatBps(rateBps)} per annum`, money(amount), true);
    canvas.text(
      `Simple interest on ${money(claim.outstanding.amount)} at ${formatBps(rateBps)} per annum, ` +
        `for the ${days} day(s) from ${fromDate} to ${toDate}, on a 365-day year.`,
      { size: 8, color: MUTED },
    );
  }

  canvas.gap(4);
  figure(canvas, 'Total amount now demanded', money(claim.totalClaimedPaise), true);
  canvas.gap(6);

  figure(canvas, 'Handover of the property', model.tenancy.handoverDate ?? '-');
  figure(
    canvas,
    `Refund due by (handover plus ${model.rules.refundWindowDays} days)`,
    claim.refundDueDate,
  );
  figure(canvas, 'Days past the refund date, as at ' + claim.asOfDate, String(claim.daysOverdue));
  if (model.refundReceivedDate) {
    figure(canvas, 'Part refund received on', model.refundReceivedDate);
  }
}

function drawReasons(canvas: Canvas, model: LetterModel): void {
  if (model.deductionReasons.length === 0) return;

  canvas.gap(8);
  canvas.text('Reasons given by the landlord for the deductions', { size: 12, bold: true });
  canvas.rule();
  // Framed as theirs. The letter neither adopts these nor argues with them; it
  // sets the record beside them and leaves the comparison to the reader.
  canvas.text('Reproduced as stated by the landlord. The tenant does not accept them.', {
    size: 9,
    color: MUTED,
  });
  canvas.gap(2);

  for (const reason of model.deductionReasons) {
    for (const [i, line] of wrap(reason, canvas.font.body, 10, CONTENT_WIDTH - 14).entries()) {
      canvas.text(i === 0 ? `-  ${line}` : line, { size: 10, indent: i === 0 ? 0 : 14 });
    }
  }
}

function drawPhotoLine(canvas: Canvas, photo: ReportPhoto): void {
  canvas.text(`${photo.photoId}  —  received ${photo.receivedAt} (server clock)`, {
    size: 8,
    indent: 12,
  });
  canvas.text(`SHA-256 ${photo.sha256}`, { size: 7, mono: true, color: MUTED, indent: 12 });
  if (photo.exifCapturedAt) {
    canvas.text(`Camera reported ${photo.exifCapturedAt} (not independently verified)`, {
      size: 7,
      color: MUTED,
      indent: 12,
    });
  }
}

function drawRoom(canvas: Canvas, room: LetterRoom): void {
  canvas.reserve(60);
  canvas.gap(8);
  canvas.text(
    `${room.label}  —  ${room.movein.length} photograph(s) at move-in, ` +
      `${room.moveout.length} at move-out`,
    { size: 11, bold: true },
  );
  canvas.rule();

  for (const [heading, photos] of [
    ['At move-in', room.movein],
    ['At move-out', room.moveout],
  ] as const) {
    canvas.text(heading, { size: 9, bold: true });
    if (photos.length === 0) {
      // Stated rather than omitted: an absent heading invites the reader to
      // assume photographs exist that do not.
      canvas.text('No photographs were recorded for this room in this phase.', {
        size: 8,
        color: MUTED,
        indent: 12,
      });
      continue;
    }
    for (const photo of photos) drawPhotoLine(canvas, photo);
  }

  canvas.gap(2);
  canvas.text('Recorded changes', { size: 9, bold: true });

  if (room.recordedChanges.length === 0) {
    canvas.text('The tenant recorded no changes for this room.', {
      size: 8,
      color: MUTED,
      indent: 12,
    });
    return;
  }

  for (const change of room.recordedChanges) {
    canvas.reserve(40);
    canvas.text(
      `${change.type}${change.surface ? ` / ${change.surface}` : ''} — ${change.location}`,
      { size: 9, bold: true, indent: 12 },
    );
    for (const line of wrap(change.description, canvas.font.body, 9, CONTENT_WIDTH - 24)) {
      canvas.text(line, { size: 9, indent: 24 });
    }
    // The §9.7 / `demo-safety` marker, on the same page as the assertion.
    canvas.text(ORIGIN_LABEL[change.origin], { size: 8, color: MUTED, indent: 24 });

    if (change.wearAndTear) {
      // Both sides or neither — there is no verdict to render.
      for (const [label, text] of [
        ['A landlord may argue:', change.wearAndTear.landlordMayArgue],
        ['Tenants typically counter:', change.wearAndTear.tenantsTypicallyCounter],
      ] as const) {
        canvas.text(label, { size: 8, bold: true, indent: 24, color: MUTED });
        for (const line of wrap(text, canvas.font.body, 8, CONTENT_WIDTH - 36)) {
          canvas.text(line, { size: 8, indent: 36, color: MUTED });
        }
      }
    }
    canvas.gap(4);
  }
}

function drawStatutory(canvas: Canvas, model: LetterModel): void {
  const { rules } = model;

  canvas.gap(10);
  canvas.text('Statutory references and next steps', { size: 12, bold: true });
  canvas.rule();

  canvas.text(`State: ${rules.stateName} (${rules.stateCode})`, { size: 10 });
  canvas.text(`Forum named for disputes of this kind: ${rules.authorityName}`, { size: 10 });
  canvas.gap(2);

  for (const ref of rules.statuteRefs) {
    canvas.text(ref.citation, { size: 9, bold: true });
    for (const line of wrap(ref.title, canvas.font.body, 8, CONTENT_WIDTH - 12)) {
      canvas.text(line, { size: 8, color: MUTED, indent: 12 });
    }
    if (ref.url) canvas.text(ref.url, { size: 8, color: MUTED, indent: 12 });
  }

  if (rules.escalationSteps.length > 0) {
    canvas.gap(4);
    canvas.text('If this demand is not met', { size: 10, bold: true });
    for (const step of rules.escalationSteps) {
      canvas.text(
        `${step.order + 1}. ${step.label}` +
          (step.afterDays !== undefined ? `  (after ${step.afterDays} day(s))` : ''),
        { size: 9, bold: true },
      );
      for (const line of wrap(step.description, canvas.font.body, 8, CONTENT_WIDTH - 12)) {
        canvas.text(line, { size: 8, color: MUTED, indent: 12 });
      }
    }
  }

  canvas.gap(6);
  // R9. Exactly one of these two is printed, and which one is decided by
  // whether a human set a review date — never by this renderer.
  if (rules.reviewed && rules.lastReviewedAt) {
    canvas.text(`These statutory references were last reviewed on ${rules.lastReviewedAt}.`, {
      size: 8,
      color: MUTED,
    });
  } else {
    for (const line of RULES_UNREVIEWED) canvas.text(line, { size: 8, color: MUTED });
  }
}

/* ── Entry point ───────────────────────────────────────────────────────────── */

export interface RenderedLetter {
  readonly bytes: Uint8Array;
  readonly pageCount: number;
}

/**
 * Render a demand letter model to PDF bytes.
 *
 * No images: the letter references the evidence by digest and timestamp and
 * points at the Condition and Exit Reports for the photographs themselves.
 * That keeps the letter a document a person will actually read, and keeps the
 * photographs in the report whose whole purpose is to carry them.
 */
export async function renderLetter(
  model: LetterModel,
  recordRef: string,
): Promise<RenderedLetter> {
  const doc = await PDFDocument.create({ updateMetadata: false });

  const fonts: Fonts = {
    body: await doc.embedFont(StandardFonts.Helvetica),
    bold: await doc.embedFont(StandardFonts.HelveticaBold),
    mono: await doc.embedFont(StandardFonts.Courier),
  };

  // Determinism (§5.6): metadata from the model, never from the clock.
  const generated = new Date(model.generatedAt);
  doc.setTitle(TITLE);
  doc.setProducer('Handover');
  doc.setCreator('Handover');
  doc.setCreationDate(generated);
  doc.setModificationDate(generated);

  const canvas = new Canvas(doc, fonts);

  canvas.text(TITLE, { size: 18, bold: true });
  canvas.text(`Dated ${model.generatedAt.slice(0, 10)}`, { size: 10, color: MUTED });
  canvas.gap(6);
  canvas.rule();

  canvas.text(model.tenancy.addressLine, { size: 11, bold: true });
  canvas.text(`${model.tenancy.city}, ${model.tenancy.stateCode}`, { size: 10 });
  canvas.text(`Tenancy began ${model.tenancy.moveInDate}`, { size: 9, color: MUTED });
  canvas.gap(6);

  for (const line of OPENING) canvas.text(line, { size: 9 });
  canvas.gap(8);

  drawSummary(canvas, model);
  drawReasons(canvas, model);

  canvas.gap(10);
  canvas.text('Annexure — the record of condition', { size: 12, bold: true });
  canvas.rule();
  canvas.text(
    `${model.evidence.totals.roomCount} room(s), ${model.evidence.totals.photoCount} ` +
      `photograph(s), ${model.evidence.totals.recordedChangeCount} recorded change(s)`,
    { size: 9 },
  );
  canvas.gap(2);
  for (const line of ANNEXURE_NOTE) canvas.text(line, { size: 8, color: MUTED });
  canvas.gap(2);
  for (const line of CHANGES_NOTE) canvas.text(line, { size: 8, color: MUTED });

  for (const room of model.evidence.rooms) drawRoom(canvas, room);

  drawStatutory(canvas, model);

  canvas.gap(10);
  canvas.rule();
  for (const line of DISCLAIMER) canvas.text(line, { size: 8, color: MUTED });

  const pageCount = drawFooters(doc, fonts, recordRef);

  return { bytes: await doc.save({ useObjectStreams: false }), pageCount };
}
