/**
 * Condition / Exit Report rendering — architecture.md §5.6; `demo-safety`.
 *
 * "Deterministic template assembly with embedded images, hashes, timestamps,
 * and a footer record ID." Every word this file prints is either a constant
 * below or a value from `ReportModel`, which was built by pure domain code.
 * **Nothing here is model-generated**, and there is no code path by which it
 * could be: the renderer never sees a model, a prompt or a port.
 *
 * ── The copy rules, enforced here ───────────────────────────────────────────
 * `demo-safety` sets hard limits on what a document may say, and the strings
 * in this file are where they either hold or fail:
 *
 *  - **Tamper-evidence, never admissibility.** The report says what it *is* —
 *    dated, hashed, unmodified since capture — and never what a court will
 *    accept. The hashes are self-generated, so a challenger can argue the
 *    operator produced them (R4); claiming more than "unmodified since we
 *    recorded it" would be claiming something this system cannot support.
 *  - **No verdict.** Nothing states who is responsible, and wear-and-tear
 *    appears only as two opposed arguments.
 *  - **A visible marker on every model-derived assertion.** An accepted
 *    suggestion is labelled as one, distinctly from a change the tenant wrote.
 *  - **EXIF stripped from the embedded derivative**, never from the original.
 *
 * ── Determinism ─────────────────────────────────────────────────────────────
 * §5.6 calls the assembly deterministic and it is kept literally so: pdf-lib
 * is given a fixed creation and modification date taken from the model rather
 * than the clock, and no id, so re-rendering the same model byte-for-byte
 * produces the same PDF and therefore the same document hash. A report whose
 * hash changed every time it was generated would undermine the one property
 * the rest of the system is built on.
 */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { stripJpegMetadata } from '../../domain/evidence/strip-metadata.js';
import type { PDFFont, PDFImage, PDFPage } from 'pdf-lib';
import type { ReportModel, ReportPhoto, ReportRoom } from '../../domain/documents/report-model.js';

/* ── Fixed copy ────────────────────────────────────────────────────────────── */

const TITLE: Readonly<Record<ReportModel['docType'], string>> = {
  CONDITION_REPORT: 'Property Condition Report',
  EXIT_REPORT: 'Property Exit Report',
};

const SUBTITLE: Readonly<Record<ReportModel['docType'], string>> = {
  CONDITION_REPORT: 'Record of property condition at move-in',
  EXIT_REPORT: 'Record of property condition at move-out, with the move-in record',
};

/**
 * The integrity statement. Read it as three claims, each of which this system
 * can actually support: we recorded these at these times, by our clock; this
 * is the digest of what we stored; the stored object has not been rewritten.
 *
 * Note what it does not say. Not "admissible", not "proof", not "verified by"
 * anyone. The last line is the honest caveat — the hashes are ours — and it
 * stays in even though it weakens the document, because a reader who later
 * discovers it themselves has been misled by its absence.
 */
const INTEGRITY_NOTE = [
  'Each photograph below was timestamped by this service when it was received, and a',
  'SHA-256 digest was computed from the stored file at that moment. The stored files are',
  'never rewritten, so a digest recomputed from one today will match the value printed here',
  'if and only if the file is unchanged since capture.',
  'These digests are generated by this service and are evidence of tamper-evidence, not of',
  'authenticity independently certified by a third party.',
];

const CHANGE_SECTION_NOTE = [
  'The tenant recorded the following changes between the two sets of photographs. Each entry',
  'is shown with how it came to be on this record. This document reaches no conclusion about',
  'responsibility for any change, or about whether any change is normal wear and tear.',
];

const ORIGIN_LABEL: Readonly<Record<string, string>> = {
  TENANT_RECORDED: 'Recorded by the tenant',
  TENANT_ACCEPTED_SUGGESTION: 'Software suggestion, reviewed and accepted by the tenant',
};

/* ── Layout ────────────────────────────────────────────────────────────────── */

const PAGE = { width: 595.28, height: 841.89 } as const; // A4 portrait, points
const MARGIN = 48;
const CONTENT_WIDTH = PAGE.width - MARGIN * 2;

const INK = rgb(0.1, 0.1, 0.12);
const MUTED = rgb(0.42, 0.42, 0.46);
const RULE = rgb(0.85, 0.85, 0.88);

interface Fonts {
  readonly body: PDFFont;
  readonly bold: PDFFont;
  readonly mono: PDFFont;
}

/** A cursor over a growing document, so callers never track page breaks. */
class Canvas {
  #doc: PDFDocument;
  #fonts: Fonts;
  #page: PDFPage;
  #y: number;
  readonly pages: PDFPage[] = [];

  constructor(doc: PDFDocument, fonts: Fonts) {
    this.#doc = doc;
    this.#fonts = fonts;
    this.#page = this.#newPage();
    this.#y = PAGE.height - MARGIN;
  }

  #newPage(): PDFPage {
    const page = this.#doc.addPage([PAGE.width, PAGE.height]);
    this.pages.push(page);
    return page;
  }

  /** Ensure `height` points are available, breaking to a new page if not. */
  reserve(height: number): void {
    if (this.#y - height < MARGIN + 28) {
      this.#page = this.#newPage();
      this.#y = PAGE.height - MARGIN;
    }
  }

  text(
    value: string,
    options: { size?: number; bold?: boolean; mono?: boolean; color?: ReturnType<typeof rgb>; indent?: number } = {},
  ): void {
    const size = options.size ?? 10;
    const font = options.mono ? this.#fonts.mono : options.bold ? this.#fonts.bold : this.#fonts.body;
    this.reserve(size + 4);
    this.#y -= size + 2;
    this.#page.drawText(sanitise(value), {
      x: MARGIN + (options.indent ?? 0),
      y: this.#y,
      size,
      font,
      color: options.color ?? INK,
    });
    this.#y -= 2;
  }

  gap(points = 8): void {
    this.#y -= points;
  }

  rule(): void {
    this.reserve(10);
    this.#y -= 6;
    this.#page.drawLine({
      start: { x: MARGIN, y: this.#y },
      end: { x: MARGIN + CONTENT_WIDTH, y: this.#y },
      thickness: 0.5,
      color: RULE,
    });
    this.#y -= 6;
  }

  image(image: PDFImage, width: number, height: number): void {
    this.reserve(height + 6);
    this.#y -= height;
    this.#page.drawImage(image, { x: MARGIN, y: this.#y, width, height });
    this.#y -= 4;
  }

  get font(): Fonts {
    return this.#fonts;
  }
}

/**
 * WinAnsi cannot encode every character a tenant might type, and pdf-lib
 * throws on one it cannot draw — which would fail the whole document over a
 * curly quote. Replacing the common typographic characters and dropping the
 * rest keeps a stray character from costing the tenant their report.
 */
function sanitise(value: string): string {
  return value
    .replace(/[‘’‛]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[–—]/g, '-')
    .replace(/…/g, '...')
    .replace(/[^\x20-\x7E]/g, '');
}

/** Wrap to the content width, measured in the font it will be drawn in. */
function wrap(value: string, font: PDFFont, size: number, width = CONTENT_WIDTH): string[] {
  const words = sanitise(value).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = '';

  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= width) {
      line = candidate;
      continue;
    }
    if (line) lines.push(line);
    line = word;
  }
  if (line) lines.push(line);
  return lines.length > 0 ? lines : [''];
}

function formatBytes(bytes: number): string {
  return bytes >= 1024 * 1024
    ? `${(bytes / (1024 * 1024)).toFixed(2)} MB`
    : `${Math.round(bytes / 1024)} KB`;
}

/* ── Photographs ───────────────────────────────────────────────────────────── */

/** The fetched bytes of one photograph, keyed by the model's `s3Key`. */
export type ImageBytes = ReadonlyMap<string, Uint8Array>;

const MAX_IMAGE_HEIGHT = 260;

/**
 * Embed one photograph, with its evidence line underneath.
 *
 * The bytes are stripped of metadata **here**, at the moment of embedding, so
 * there is no route by which an un-stripped image reaches a page: a caller
 * cannot forget, because the caller never hands bytes to pdf-lib itself.
 *
 * An image that cannot be embedded still gets its evidence line. The hash and
 * the timestamp are the record; the picture is an illustration of it, and a
 * missing illustration must not take the record with it.
 */
async function drawPhoto(
  doc: PDFDocument,
  canvas: Canvas,
  photo: ReportPhoto,
  images: ImageBytes,
): Promise<void> {
  const raw = images.get(photo.s3Key);

  if (raw) {
    try {
      const safe = stripJpegMetadata(raw);
      const embedded =
        safe[0] === 0x89 && safe[1] === 0x50
          ? await doc.embedPng(safe)
          : await doc.embedJpg(safe);

      const scale = Math.min(CONTENT_WIDTH / embedded.width, MAX_IMAGE_HEIGHT / embedded.height, 1);
      canvas.image(embedded, embedded.width * scale, embedded.height * scale);
    } catch {
      canvas.text('[photograph could not be rendered; its record is below]', {
        size: 8,
        color: MUTED,
      });
    }
  } else {
    canvas.text('[photograph not attached to this copy; its record is below]', {
      size: 8,
      color: MUTED,
    });
  }

  canvas.text(`Received ${photo.receivedAt} (server clock)`, { size: 8, color: MUTED });
  if (photo.exifCapturedAt) {
    canvas.text(`Camera reported ${photo.exifCapturedAt} (not independently verified)`, {
      size: 8,
      color: MUTED,
    });
  }
  canvas.text(`SHA-256 ${photo.sha256}`, { size: 7, mono: true, color: MUTED });
  canvas.text(`${formatBytes(photo.bytes)} · reference ${photo.photoId}`, {
    size: 8,
    color: MUTED,
  });
  canvas.gap(6);
}

/* ── Sections ──────────────────────────────────────────────────────────────── */

async function drawRoom(
  doc: PDFDocument,
  canvas: Canvas,
  room: ReportRoom,
  model: ReportModel,
  images: ImageBytes,
): Promise<void> {
  canvas.reserve(60);
  canvas.gap(10);
  canvas.text(room.label, { size: 13, bold: true });
  canvas.rule();

  const sections: Array<[string, readonly ReportPhoto[]]> =
    model.phase === 'MOVEOUT'
      ? [
          ['At move-in', room.movein],
          ['At move-out', room.moveout],
        ]
      : [['At move-in', room.movein]];

  for (const [heading, photos] of sections) {
    canvas.text(heading, { size: 10, bold: true });
    if (photos.length === 0) {
      // Stated, not omitted. "No photographs were recorded" is a fact about
      // the record; an absent heading is an invitation to assume otherwise.
      canvas.text('No photographs were recorded for this room in this phase.', {
        size: 9,
        color: MUTED,
      });
      canvas.gap(4);
      continue;
    }
    for (const photo of photos) {
      await drawPhoto(doc, canvas, photo, images);
    }
  }

  if (model.phase !== 'MOVEOUT') return;

  canvas.text('Recorded changes', { size: 10, bold: true });

  if (room.recordedChanges.length === 0) {
    canvas.text('The tenant recorded no changes for this room.', { size: 9, color: MUTED });
    canvas.gap(4);
    return;
  }

  for (const change of room.recordedChanges) {
    canvas.reserve(46);
    canvas.text(`${change.type}${change.surface ? ` · ${change.surface}` : ''} — ${change.location}`, {
      size: 9,
      bold: true,
    });
    for (const line of wrap(change.description, canvas.font.body, 9, CONTENT_WIDTH - 12)) {
      canvas.text(line, { size: 9, indent: 12 });
    }
    // The §9.7 marker: what kind of assertion this is, on the same page as it.
    canvas.text(ORIGIN_LABEL[change.origin] ?? change.origin, {
      size: 8,
      color: MUTED,
      indent: 12,
    });

    if (change.wearAndTear) {
      // Both sides or neither — there is no verdict to render.
      for (const [label, text] of [
        ['A landlord may argue:', change.wearAndTear.landlordMayArgue],
        ['Tenants typically counter:', change.wearAndTear.tenantsTypicallyCounter],
      ] as const) {
        canvas.text(label, { size: 8, bold: true, indent: 12, color: MUTED });
        for (const line of wrap(text, canvas.font.body, 8, CONTENT_WIDTH - 24)) {
          canvas.text(line, { size: 8, indent: 24, color: MUTED });
        }
      }
    }
    canvas.gap(6);
  }
}

/* ── Entry point ───────────────────────────────────────────────────────────── */

export interface RenderedReport {
  readonly bytes: Uint8Array;
  readonly pageCount: number;
}

/**
 * Render a report model to PDF bytes.
 *
 * `images` maps `ReportPhoto.s3Key` to the fetched original bytes. Keys the
 * caller could not fetch may simply be absent; the record still prints.
 */
export async function renderReport(
  model: ReportModel,
  recordRef: string,
  images: ImageBytes = new Map(),
): Promise<RenderedReport> {
  const doc = await PDFDocument.create({ updateMetadata: false });

  const fonts: Fonts = {
    body: await doc.embedFont(StandardFonts.Helvetica),
    bold: await doc.embedFont(StandardFonts.HelveticaBold),
    mono: await doc.embedFont(StandardFonts.Courier),
  };

  // Determinism (§5.6): metadata comes from the model, never from the clock,
  // so the same model always hashes to the same document.
  const generated = new Date(model.generatedAt);
  doc.setTitle(TITLE[model.docType]);
  doc.setProducer('Handover');
  doc.setCreator('Handover');
  doc.setCreationDate(generated);
  doc.setModificationDate(generated);

  const canvas = new Canvas(doc, fonts);

  canvas.text(TITLE[model.docType], { size: 18, bold: true });
  canvas.text(SUBTITLE[model.docType], { size: 10, color: MUTED });
  canvas.gap(6);
  canvas.rule();

  canvas.text(model.tenancy.addressLine, { size: 11, bold: true });
  canvas.text(`${model.tenancy.city}, ${model.tenancy.stateCode}`, { size: 10 });
  canvas.text(`Tenancy began ${model.tenancy.moveInDate}`, { size: 9, color: MUTED });
  if (model.tenancy.handoverDate) {
    canvas.text(`Handover ${model.tenancy.handoverDate}`, { size: 9, color: MUTED });
  }
  canvas.text(`Generated ${model.generatedAt}`, { size: 9, color: MUTED });
  canvas.gap(8);

  canvas.text('How to read this record', { size: 10, bold: true });
  for (const line of INTEGRITY_NOTE) {
    canvas.text(line, { size: 8, color: MUTED });
  }
  canvas.gap(4);

  canvas.text(
    `${model.totals.roomCount} room(s) · ${model.totals.photoCount} photograph(s)` +
      (model.phase === 'MOVEOUT'
        ? ` · ${model.totals.recordedChangeCount} recorded change(s)`
        : ''),
    { size: 9 },
  );

  if (model.phase === 'MOVEOUT') {
    canvas.gap(4);
    for (const line of CHANGE_SECTION_NOTE) {
      canvas.text(line, { size: 8, color: MUTED });
    }
  }

  for (const room of model.rooms) {
    await drawRoom(doc, canvas, room, model, images);
  }

  // Footer on every page, drawn last so the page count is known.
  const pages = doc.getPages();
  pages.forEach((page, index) => {
    page.drawText(sanitise(`${recordRef}  ·  page ${index + 1} of ${pages.length}`), {
      x: MARGIN,
      y: MARGIN - 18,
      size: 7,
      font: fonts.mono,
      color: MUTED,
    });
  });

  return { bytes: await doc.save({ useObjectStreams: false }), pageCount: pages.length };
}
